#!/usr/bin/env bash
# This script displays information about each user in /etc/passwd formated like a story

while IFS=':' read -r username _ uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. User ID's place is protected by the passcode $info, more info about the user here: $uid"
done < /etc/passwd
