#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data sorted by the number of occurrences

awk '{arr[$1 " " $9]++} END {for (i in arr) print arr[i], i}' apache-access.log | sort -nr
