#!/usr/bin/env bash
# the script prints "Best School" 10 times, if its the 9th itteration it also prints "Hi"
count=0
while [ $count -lt 10 ]; do
    echo "Best School"
    if [ $count -eq 8 ]; then
	echo "Hi"
    fi
    count=$((count + 1))
done
