#!/usr/bin/env bash
# the script prints "Best School" 10 times
count=0
while [ $count -lt 10 ]; do
    if [ $count -eq 2 ]; then
	echo "bad luck"
    elif [ $count -eq 7 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    count=$((count + 1))
done
